services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./temp_uploads:/app/temp_uploads
    depends_on:
      mongo:
        condition: service_started
    environment:
      - OLLAMA_HOST=http://host.docker.internal:11434
      - MONGODB_URI=${MONGO_URI}
      - CONCURRENT_REQUESTS=2
      - OLLAMA_REQUEST_TIMEOUT=600
      - AWS_REGION=${AWS_REGION:-us-east-2}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME:-pdf-question-bank}
      - SQS_DLQ_URL=${SQS_DLQ_URL:-YOUR_SQS_DLQ_URL}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-YOUR_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-YOUR_SECRET_KEY}
      - PROCESSING_TIMEOUT=${PROCESSING_TIMEOUT:-900}
      - MAX_RETRY_ATTEMPTS=${MAX_RETRY_ATTEMPTS:-3}

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=question_bank

volumes:
  mongo_data: